-- Database Schema for Supabase URL Shortener

-- 1. Create urls table
CREATE TABLE IF NOT EXISTS public.urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    short_key TEXT UNIQUE NOT NULL,
    original_url TEXT NOT NULL,
    custom_alias TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_urls_short_key ON public.urls(short_key);
CREATE INDEX IF NOT EXISTS idx_urls_user_id ON public.urls(user_id);
CREATE INDEX IF NOT EXISTS idx_urls_expires_at ON public.urls(expires_at) WHERE expires_at IS NOT NULL;

-- Enable Row Level Security (RLS) on urls
ALTER TABLE public.urls ENABLE ROW LEVEL SECURITY;

-- Policies for urls
CREATE POLICY "Allow public read of active urls" ON public.urls
    FOR SELECT
    USING (is_active = TRUE);

CREATE POLICY "Allow authenticated users to insert their own urls" ON public.urls
    FOR INSERT
    WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Allow creators to update their own urls" ON public.urls
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow creators to delete their own urls" ON public.urls
    FOR DELETE
    USING (auth.uid() = user_id);


-- 2. Create analytics table
CREATE TABLE IF NOT EXISTS public.analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_key TEXT NOT NULL REFERENCES public.urls(short_key) ON DELETE CASCADE,
    clicked_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    country_code CHAR(2),
    user_agent TEXT,
    referrer TEXT
);

-- Indexing for analytics queries
CREATE INDEX IF NOT EXISTS idx_analytics_short_key_date ON public.analytics(short_key, clicked_at DESC);

-- Enable Row Level Security (RLS) on analytics
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- Policies for analytics
CREATE POLICY "Allow anyone to insert click analytics" ON public.analytics
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow creators to view analytics of their own urls" ON public.analytics
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.urls
            WHERE public.urls.short_key = public.analytics.short_key
            AND public.urls.user_id = auth.uid()
        )
    );

-- Restart sequence at 56800235584 to guarantee all base62 auto-generated keys are at least 7 characters
ALTER SEQUENCE IF EXISTS public.urls_id_seq RESTART WITH 56800235584;
